### ISSUE TITLE
inference detail

### ISSUE THREAD

**Issue by Yxxxb** [jayelm/gisting#18]
Nice work!

I have some question about the inference preocess.

First the [prompt, gist tokens] is feed into the model to get gist tokens, and then the [gist tokens, query] is feed into the model to generate a response for the query.

So which is the input gist tokens of [gist tokens, query] in the second stage?
1. output embedding of the gist token 
2. the tokenized token of the gist token 
3. the text output of the gist token

And could you provide the inference code if possible?

thx

**Comment by jayelm** [comment]
Hi, thanks for your interest!

The input of the second stage are the transformer activations on top of the gist token embeddings computed in the first stage. Regarding the 3 options you listed above:

1. output embedding of the gist token: it's not just the word embeddings of the gist token, but rather all of the transformer layers on top as well.
2. the tokenized token of the gist token: you don't need this in the second stage since all you depend upon is the transformer prefix
3. the text output of the gist token: I'm not sure what you mean by this, there is no text output associated with the gist tokens, they are only embedded and used to decode the LM output

Inference code is in this repository! See `src/compress.py` in the readme. https://github.com/jayelm/gisting?tab=readme-ov-file#demo--checkpoints

**Comment by Yxxxb** [comment]
thx for your reply, i'll check the compress.py later, nice work again!
